apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: tts
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location /api/text {
          proxy_pass http://text-service:8080;
        }

        location /process {
          proxy_pass http://speech-service:8081;
        }
      }
    }
